### ISSUE TITLE
Binary dependencies needed?

### ISSUE THREAD

**Issue by jrgonzalezg** [TeamWanari/HugeMapMaker#1]
Very interesting library :). I have been testing it a bit and it looks very promising, but it seems to be adding 2-3 Mb to the app apks for no clear reason.

I think it is due to the library being configured to use renderscript (which leads to including several native libraries in the .aar) as well as some additional binary libs (without source code) on library/src/main/obj . As far as i could see neither of these are needed or are not being used and they could be removed to make the library weight a lot less.

**Comment by agta1991** [comment]
While I was experimenting with different implementations, I might have left some of them in. I will remove it as soon as I have time.
