### ISSUE TITLE
Custom marker support?

### ISSUE THREAD

**Issue by jrgonzalezg** [TeamWanari/HugeMapMaker#2]
I have seen in the future improvements a task to "Make markers customizable" and i really think this is a must have to be able to use this library on more projects.

But i have some questions about this topic in order to evaluate if it could be used to completely replace the Google Map's markers:
- Will the custom markers also support click listeners / custom info windows? I am not sure how difficult will be to support this with this type of OpenGL implementation or if you already have some ideas on how it could be done.
- Do you have any expected timeline for releasing this additional features?

Thanks!

**Comment by agta1991** [comment]
The library itself is not designed for user interactions it's only supposed to enable more markers displayed than the original Maps library can. However the combination of the two will still allow you interactions like click-handling, if you use the setOnMapClickListener on the MapView, you can filter out the closest marker (which is displayed with this lib) and use the MapView to show an InfoWindow.
